### ISSUE TITLE
11/9 목 스크럼

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/test#4]
# 투두리스트 작성하는 법
### 참고사항
본인의 작업 코드에 해당하는 이슈 링크 첨부 권장 (그 사람이 전체적인 작업 현황을 쉽게 볼 수 있으면 좋겠다는 의견)

**Comment by heehoh** [comment]
- [ ] 탈퇴 시 로그아웃하고 메인페이지로 이동 구현
- [ ] 탈퇴 기능 QA

**Comment by joonseong11** [comment]
- [ ] (외주) 과업지시서, 견적서, 계약서 관련 서류 준비
- [ ] (외주) 저녁 클라이언트 미팅
- [ ] (peer) 모집글쓰기 변경된 태그 api 반영
- [ ] (peer) 모집글쓰기 모집인터뷰에서 데이터 타입이 맞지 않는 문제 발견 (시간이 좀 걸릴것같음)

**Comment by SaltySalt77** [comment]
- [ ] 알림 키워드 버그 있던 부분 고쳐졌는지 확인
- [ ] 하류님과 자동화 작업(?)

**Comment by yoouyeon** [comment]
- [ ] 쪽지 전체 선택 기능 보완
  - [ ] 전체 선택 / 전체 선택 해제
  - [ ] 전체 선택 및 해제 시 체크박스에 보여주기
- [ ] 프로필 페이지 QA

**Comment by juhyeonlee134** [comment]
- [ ] 모집 글쓰기 QA진행
- [ ] 남아있는 프로필 PR 머지

**Comment by weejihye** [comment]
- [ ] https://github.com/peer-42seoul/Peer-Backend/issues/292
- [ ] https://github.com/peer-42seoul/Peer-Backend/issues/276
- [ ] https://github.com/peer-42seoul/Peer-Backend/issues/230
- [ ] https://github.com/peer-42seoul/Peer-Backend/issues/198

**Comment by hyeon81** [comment]
- [ ] 메인페이지 세부옵션 검색 필터링 적용되도록 api 연결 부분 수정
- [ ] 폼페이지 지원 부분 api 잘되는지 테스트
- [ ] useSWRinfinite 공부
- [ ] pr 확인

- [ ] 외주 작업 처리

**Comment by KRimwoo** [comment]
- [ ] config.ts 로직 최종 점검해서 pr다시올리기
- [ ] 소셜 연동 회원가입 테스트

**Comment by sinryuji** [comment]
- [ ] 구글 OAuth 에러 고치기
- [ ] 사용자 추적 팀파트 개발

**Comment by wochae** [comment]
- [ ] (피어) 어제 회의록 내용 숙지
- [ ] (피어) https://github.com/peer-42seoul/Peer-Frontend/issues/221#issue-1975724926 부터 QA 확인 시작하기
- [ ] 우테코 과제 피드백

**Comment by perman0519** [comment]
- [ ] (피어) dnd 및 몽고db 공부
- [ ] 자바 과제 풀이 마무리

**Comment by Paul2021-R** [comment]
- [ ] (피어) 개선 프로세스 적용작업
- [ ] monogoDB 학습
- [ ] 담당 파트 문서화 시작
